---
title: "Salamanders!"
author: "Allison Hacker and Cameryn Brock"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Attache packages
library(tidyverse)
library(janitor)
library(kableExtra)

# Read in data
salamanders <- read_csv("mack_creek_vertebrates.csv") %>% 
  clean_names() %>% 
  filter(species == "DITE")
```

### Introduction
### Data and Methods
### Results

```{r}
# Part A : Annual salamander counts by year

salamander_count <- salamanders %>% 
  group_by(section, year) %>% 
  summarize(n = n())

ggplot(salamander_count, aes(x = year, y = n))+
  geom_line(aes(color = section))+
  geom_point(aes(color = section))+
  theme_minimal()+
  labs(x = "Year", y = "Number of Salamanders")

```


```{r}
# Part B: 2017 salamander counts by channel classification

channel_class <- salamanders %>% 
  filter(year == 2017,
         unittype != "IP") %>% 
  mutate(unittype = case_when(unittype == "C" ~ "Cascade",
                              unittype == "P" ~ "Pool",
                              unittype == "SC" ~ "Side Channel")) %>% 
  group_by(section, unittype) %>% 
  summarize(n = n())
  
 channel_class_wide <- channel_class %>% 
   pivot_wider(names_from = section, values_from = n)

channel_class_props <- channel_class_wide %>% 
  adorn_percentages(denominator = "col") %>% 
  adorn_pct_formatting(digits = 1) %>% 
  adorn_ns(position = "front")

kable(channel_class_props, 
      align = "c",
      col.names = c("Channel Classification",
                    "Clear Cut",
                    "Old Growth")
      ) %>% 
  kable_styling(bootstrap_options = c("hover"))
```


```{r}
# Part C: ANOVA for effect of forest condition on preferred channel classification
channel_counts <- channel_class_wide %>% 
  select(-unittype)

channel_chi <- chisq.test(channel_counts)
channel_chi
```
 There is no significant association between creek section and the channel classification where salamanders are found.
